# Generated by Django 2.2.4 on 2019-09-16 03:49

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Albom',
            },
        ),
        migrations.CreateModel(
            name='Awtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=256)),
                ('familiyasy', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Awtor',
            },
        ),
        migrations.CreateModel(
            name='Bilim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField(default='')),
                ('makala_ru', ckeditor.fields.RichTextField(default='')),
                ('makala_en', ckeditor.fields.RichTextField(default='')),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Bilim')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bilim',
            },
        ),
        migrations.CreateModel(
            name='Bilmek_Gyzykly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Bilmek_Gyzykly')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bilmek_Gyzykly',
            },
        ),
        migrations.CreateModel(
            name='Doredijilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Doredijilik')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Doredijilik',
            },
        ),
        migrations.CreateModel(
            name='Fayl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('mazmun_tm', ckeditor.fields.RichTextField()),
                ('mazmun_ru', ckeditor.fields.RichTextField()),
                ('mazmun_en', ckeditor.fields.RichTextField()),
                ('pdf', models.FileField(upload_to='Fayl')),
                ('Ikonka', models.ImageField(upload_to='Fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fayl',
            },
        ),
        migrations.CreateModel(
            name='Gosmaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady', models.CharField(max_length=256)),
                ('suraty', models.ImageField(upload_to='Gosmaca')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gosmaca',
            },
        ),
        migrations.CreateModel(
            name='Habar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Habar')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Habar',
            },
        ),
        migrations.CreateModel(
            name='Harby_Durmus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField(default='')),
                ('makala_ru', ckeditor.fields.RichTextField(default='')),
                ('makala_en', ckeditor.fields.RichTextField(default='')),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Harby_Durmus')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Harby_Durmus',
            },
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ady_tm', models.CharField(max_length=256)),
                ('Ady_ru', models.CharField(max_length=256)),
                ('Ady_en', models.CharField(max_length=256)),
                ('surat', models.ImageField(upload_to='Kitap')),
                ('pdf', models.FileField(upload_to='Kitap')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Kitap',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Myhman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_salgysy', models.CharField(max_length=256)),
                ('rq_sany', models.IntegerField(default=0)),
                ('now', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Myhman',
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(choices=[('Habar', 'Habar'), ('Harby_Durmus', 'Harby_Durmus'), ('Taryh', 'Taryh'), ('Sport', 'Sport'), ('Bilim', 'Bilim'), ('Doredijilik', 'Doredijilik'), ('Tehnologiya', 'Tehnologiya'), ('Bulary_Bilmek_Gyzykly', 'Bulary_Bilmek_Gyzykly')], default=1, max_length=20)),
                ('id_i', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Slideshow',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Sport')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sport',
            },
        ),
        migrations.CreateModel(
            name='Taryh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Taryh')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Taryh',
            },
        ),
        migrations.CreateModel(
            name='Tehnologiya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('makala_tm', ckeditor.fields.RichTextField()),
                ('makala_ru', ckeditor.fields.RichTextField()),
                ('makala_en', ckeditor.fields.RichTextField()),
                ('wagty', models.DateField()),
                ('okalan', models.IntegerField(default=0)),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Tehnologiya')),
                ('mohum', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tehnologiya',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ady_tm', models.CharField(max_length=256)),
                ('ady_ru', models.CharField(max_length=256)),
                ('ady_en', models.CharField(max_length=256)),
                ('video', models.FileField(upload_to='Video')),
                ('suraty', models.ImageField(upload_to='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Video',
            },
        ),
        migrations.CreateModel(
            name='Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Albom')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Albom')),
            ],
            options={
                'verbose_name_plural': 'Surat',
            },
        ),
        migrations.CreateModel(
            name='STehnologiya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Tehnologiya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tehnologiya')),
            ],
            options={
                'verbose_name_plural': 'STehnologiya',
            },
        ),
        migrations.CreateModel(
            name='STaryh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Taryh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Taryh')),
            ],
            options={
                'verbose_name_plural': 'STaryh',
            },
        ),
        migrations.CreateModel(
            name='SSport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Sport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sport')),
            ],
            options={
                'verbose_name_plural': 'SSport',
            },
        ),
        migrations.CreateModel(
            name='SHarby_Durmus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Harby_Durmus')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Harby_Durmus')),
            ],
            options={
                'verbose_name_plural': 'SHarby_Durmus',
            },
        ),
        migrations.CreateModel(
            name='SHabar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Habar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Habar')),
            ],
            options={
                'verbose_name_plural': 'SHabar',
            },
        ),
        migrations.CreateModel(
            name='SDoredijilik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Doredijilik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Doredijilik')),
            ],
            options={
                'verbose_name_plural': 'SDoredijilik',
            },
        ),
        migrations.CreateModel(
            name='SBilmek_Gyzykly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Bilmek_Gyzykly')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bilmek_Gyzykly')),
            ],
            options={
                'verbose_name_plural': 'SBilmek_Gyzykly',
            },
        ),
        migrations.CreateModel(
            name='SBilim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suraty', imagekit.models.fields.ProcessedImageField(upload_to='Bilim')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Bilim')),
            ],
            options={
                'verbose_name_plural': 'SBilim',
            },
        ),
    ]
