# Generated by Django 2.2.4 on 2019-09-16 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myhman',
            name='now',
        ),
    ]
