# Generated by Django 2.2.4 on 2019-09-16 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_myhman_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fayl',
            options={'verbose_name_plural': 'Harby_Hukuk'},
        ),
        migrations.AddField(
            model_name='kitap',
            name='Awtor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Awtor'),
        ),
    ]
