# Generated by Django 2.2.4 on 2019-09-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190916_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilim',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bilmek_gyzykly',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='doredijilik',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='habar',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='harby_durmus',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='menu',
            field=models.CharField(choices=[('Habarlar', 'Habarlar'), ('Harby_Durmus', 'Harby_Durmus'), ('Taryh', 'Taryh'), ('Sport', 'Sport'), ('Bilim', 'Bilim'), ('Doredijilik', 'Doredijilik'), ('Tehnologiya', 'Tehnologiya'), ('Bulary_Bilmek_Gyzykly', 'Bulary_Bilmek_Gyzykly')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='sport',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taryh',
            name='wagty',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tehnologiya',
            name='wagty',
            field=models.DateTimeField(),
        ),
    ]
