# Generated by Django 2.2.4 on 2019-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190916_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='wagty',
            field=models.DateTimeField(),
        ),
    ]
