# Generated by Django 2.2.4 on 2019-09-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190916_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habar',
            name='wagty',
            field=models.DateField(),
        ),
    ]
