# Generated by Django 2.2.4 on 2019-09-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190916_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harby_durmus',
            name='wagty',
            field=models.DateField(),
        ),
    ]
