# Generated by Django 2.2.4 on 2019-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190916_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilim',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bilmek_gyzykly',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doredijilik',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='harby_durmus',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sport',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='taryh',
            name='wagty',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tehnologiya',
            name='wagty',
            field=models.DateField(),
        ),
    ]
